# Generated by Django 5.0.6 on 2024-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
